
CREATE SCHEMA IF NOT EXISTS RECEIPTS;

SET SCHEMA RECEIPTS;

CREATE TABLE IF NOT EXISTS RECEIPTS (
    ID VARCHAR(255)  PRIMARY KEY,
    RETAILER VARCHAR(255) NOT NULL,
    PURCHASE_DATE VARCHAR(255) NOT NULL,
    PURCHASE_TIME VARCHAR(255) NOT NULL,
    TOTAL VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS RECEIPT_ITEMS (
    RECEIPT_ID VARCHAR(255)  ,
    PRICE VARCHAR(255),
    SHORT_DESCRIPTION VARCHAR(255) NOT NULL,
    FOREIGN KEY (RECEIPT_ID) REFERENCES RECEIPTS(ID) ON DELETE CASCADE

);

